# -*- coding: utf-8 -*-
"""Parsing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/198uvyzLTnabCuxRHGDTuc_ix0ZcT3Idw

Первый проект парсинг? да.
"""

from bs4 import BeautifulSoup
import requests
url = 'https://yandex.ru/pogoda/?lat=58.2008934&lon=68.25399017'
response = requests.get(url)
bs = BeautifulSoup(response.text,"lxml")
temp = bs.find('div', 'temp fact__temp fact__temp_size_s')
forecast = bs.find('div', 'forecast-briefly__condition') 
wind = bs.find('span', 'wind-speed')
wind2 = bs.find('span', 'fact__unit')
term = bs.find('div', 'term term_orient_v fact__humidity')
print(('Температура °:'),(temp.text))
print(('Облачность   :'),(forecast.text))
print(('Ветер        :'),(wind.text),(wind2.text))
print(('Влажность    :'),(term.text))

"""Парсинг "Яндекс.Погода". Текущая погода."""